name: DevOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Kubernetes Cluster (Kind)
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: kind

      - name: Build Docker Image
        run: docker build -t devops-lab-app:latest ./app

      - name: Load Docker Image into Kind
        run: kind load docker-image devops-lab-app:latest --name kind

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml

      - name: Verify Kubernetes Deployment
        run: |
          kubectl rollout status deployment/devops-app --timeout=60s
          kubectl get pods
          kubectl get services



